const API='https://ckiltjhcvxriwjfreqfz.supabase.co/functions/v1/profile-check-api';
const $=id=>document.getElementById(id);const views=['studentLoginView','studentEditView','teacherLoginView','teacherDashboardView'];
let studentToken=sessionStorage.getItem('studentToken')||'',adminToken=sessionStorage.getItem('adminToken')||'',student=null,students=[],changes=[],roomMap={1:[],4:[]},chartM1=null,chartM4=null,publicChartM1=null,publicChartM4=null;
const labels={prefix_th:'คำนำหน้า (ไทย)',first_name_th:'ชื่อ (ไทย)',last_name_th:'นามสกุล (ไทย)',prefix_en:'คำนำหน้า (อังกฤษ)',first_name_en:'First name',last_name_en:'Last name',phone:'เบอร์โทรศัพท์',previous_school:'โรงเรียนเดิม',room:'ห้อง',seat_number:'เลขที่','เพิ่มนักเรียน':'เพิ่มนักเรียน','ย้ายออก':'ย้ายออก','ย้ายเข้า/เปิดใช้งาน':'ย้ายเข้า/เปิดใช้งาน'};
function showView(id){views.forEach(v=>$(v).classList.toggle('active',v===id));window.scrollTo({top:0,behavior:'smooth'})}
function msg(id,text,type=''){const e=$(id);if(!e)return;e.textContent=text||'';e.className='message'+(type?' '+type:'')}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
const fullname=s=>`${s.prefix_th||''}${s.first_name_th||''} ${s.last_name_th||''}`.trim();const dtime=v=>v?new Date(v).toLocaleString('th-TH'):'';
async function api(path,{method='GET',body,token}={}){const r=await fetch(API+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'เกิดข้อผิดพลาด');return j}
async function meta(){try{const j=await api('/meta');roomMap=j.rooms||roomMap}catch{roomMap={1:[1,2,3,4,5,6,7,8,9,10,11,12,13,14],4:[1,2,3,4,5,6,7,8,9,10,11,12,13]}}fillLoginRooms()}
function fillLoginRooms(){const g=+$('loginGrade').value;$('loginRoom').innerHTML=(roomMap[g]||[]).map(r=>`<option value="${r}">ห้อง ${r}</option>`).join('')}$('loginGrade').onchange=fillLoginRooms;
$('teacherBtn').onclick=()=>showView(adminToken?'teacherDashboardView':'teacherLoginView');$('backStudentBtn').onclick=()=>showView('studentLoginView');
$('studentLoginForm').onsubmit=async e=>{e.preventDefault();msg('studentLoginMsg','กำลังตรวจสอบ...');try{const j=await api('/student/login',{method:'POST',body:{grade:+$('loginGrade').value,room:+$('loginRoom').value,student_number:$('loginStudentNumber').value.trim()}});studentToken=j.token;sessionStorage.setItem('studentToken',studentToken);loadStudent(j.student);showView('studentEditView');msg('studentLoginMsg','')}catch(err){msg('studentLoginMsg',err.message,'error')}};
function loadStudent(s){student=s;$('studentIdentity').textContent=`ม.${s.grade}/${s.room} · เลขที่ ${s.seat_number??'-'} · เลขประจำตัว ${s.student_number}`;$('fGrade').value='มัธยมศึกษาปีที่ '+s.grade;$('fRoom').value=s.room??'';$('fSeatNumber').value=s.seat_number??'';$('fStudentNumber').value=s.student_number||'';$('fPrefixTh').value=s.prefix_th||'';$('fFirstTh').value=s.first_name_th||'';$('fLastTh').value=s.last_name_th||'';$('fPhone').value=s.phone||'';$('fPrefixEn').value=s.prefix_en||'';$('fFirstEn').value=s.first_name_en||'';$('fLastEn').value=s.last_name_en||'';$('fPreviousSchool').value=s.previous_school||'';const b=$('studentStatusBanner');if(s.has_changes){b.className='status-banner changed';b.textContent=`ตรวจสอบแล้ว และมีการแก้ไขข้อมูล ${s.change_count||1} ครั้ง ล่าสุด ${dtime(s.updated_at)}`}else if(s.verified){b.className='status-banner ok';b.textContent=`ตรวจสอบข้อมูลแล้วล่าสุด ${dtime(s.verified_at||s.updated_at)}`}else{b.className='status-banner';b.textContent='กรุณาตรวจสอบข้อมูล โดยเฉพาะ “โรงเรียนเดิม” หากไม่ถูกต้องให้แก้ไขแล้วกดบันทึก'}}
function collect(){return{prefix_th:$('fPrefixTh').value.trim(),first_name_th:$('fFirstTh').value.trim(),last_name_th:$('fLastTh').value.trim(),phone:$('fPhone').value.trim(),prefix_en:$('fPrefixEn').value.trim(),first_name_en:$('fFirstEn').value.trim(),last_name_en:$('fLastEn').value.trim(),previous_school:$('fPreviousSchool').value.trim()}}
async function saveStudent(text){msg('studentSaveMsg','กำลังบันทึก...');try{const j=await api('/student/save',{method:'POST',body:{student:collect()},token:studentToken});loadStudent(j.student);const fs=j.changed_fields||[];msg('studentSaveMsg',text+'เรียบร้อยแล้ว'+(fs.length?' · แก้ไข: '+fs.map(f=>labels[f]||f).join(', '):' · ไม่มีข้อมูลเปลี่ยนแปลง'),'success');await loadPublicSummary()}catch(err){msg('studentSaveMsg',err.message,'error')}}
$('confirmBtn').onclick=()=>saveStudent('ยืนยันข้อมูล');$('studentEditForm').onsubmit=e=>{e.preventDefault();saveStudent('บันทึกข้อมูล')};$('studentLogoutBtn').onclick=async()=>{try{if(studentToken)await api('/student/logout',{method:'POST',token:studentToken})}catch{}studentToken='';student=null;sessionStorage.removeItem('studentToken');$('loginStudentNumber').value='';showView('studentLoginView')};
$('adminLoginForm').onsubmit=async e=>{e.preventDefault();msg('adminLoginMsg','กำลังเข้าสู่ระบบ...');try{const j=await api('/admin/login',{method:'POST',body:{pin:$('adminPin').value}});adminToken=j.token;sessionStorage.setItem('adminToken',adminToken);$('adminPin').value='';await refreshDashboard();showView('teacherDashboardView');msg('adminLoginMsg','')}catch(err){msg('adminLoginMsg',err.message,'error')}};
$('refreshBtn').onclick=async()=>{await refreshDashboard();await loadPublicSummary()};$('adminLogoutBtn').onclick=async()=>{try{if(adminToken)await api('/admin/logout',{method:'POST',token:adminToken})}catch{}adminToken='';sessionStorage.removeItem('adminToken');showView('teacherLoginView')};
function activeStudents(){return students.filter(s=>s.is_active!==false)}
function roomSummary(){const byGrade={1:{total:0,verified:0,pending:0,changed:0},4:{total:0,verified:0,pending:0,changed:0}},rooms={};activeStudents().forEach(s=>{const g=byGrade[s.grade]||(byGrade[s.grade]={total:0,verified:0,pending:0,changed:0});g.total++;s.verified?g.verified++:g.pending++;if(s.has_changes)g.changed++;const k=`${s.grade}-${s.room}`;const r=rooms[k]||(rooms[k]={grade:s.grade,room:s.room,total:0,verified:0,pending:0,changed:0,pendingStudents:[]});r.total++;if(s.verified)r.verified++;else{r.pending++;r.pendingStudents.push(s)}if(s.has_changes)r.changed++});return{byGrade,roomRows:Object.values(rooms).sort((a,b)=>a.grade-b.grade||a.room-b.room)}}
function renderTop(sum){const a=activeStudents(),total=a.length,verified=a.filter(s=>s.verified).length,pending=total-verified,changed=a.filter(s=>s.has_changes).length;$('kpiGrid').innerHTML=[[total,'นักเรียนทั้งหมด'],[verified,'ทำแล้ว'],[pending,'ยังไม่ทำ'],[changed,'มีการแก้ไข']].map(([n,l])=>`<div class="kpi"><strong>${n}</strong><span>${l}</span></div>`).join('');$('gradeCards').innerHTML=[1,4].map(g=>{const x=sum.byGrade[g]||{total:0,verified:0,pending:0,changed:0},p=x.total?Math.round(x.verified/x.total*100):0;return`<div class="grade-card"><h3>ภาพรวมระดับชั้น ม.${g}</h3><div class="big">${x.total} คน</div><div class="muted">ตรวจสอบแล้ว ${p}%</div><div class="mini-grid"><div class="mini"><b>${x.verified}</b><span>ทำแล้ว</span></div><div class="mini"><b>${x.pending}</b><span>ยังไม่ทำ</span></div><div class="mini"><b>${x.changed}</b><span>มีการแก้ไข</span></div></div></div>`}).join('')}
function chartOpt(rows,clickFn){return{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},onHover:(e,els)=>{e.native.target.style.cursor=els.length?'pointer':'default'},onClick:(e,els)=>{if(els.length)clickFn(rows[els[0].index])},plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:9,padding:16}},tooltip:{callbacks:{afterBody(items){const r=rows[items[0]?.dataIndex??0];return r?`นักเรียนทั้งหมด ${r.total} คน`:''}}}},scales:{x:{stacked:true,grid:{display:false},ticks:{autoSkip:false,maxRotation:0,minRotation:0,padding:6,font:{size:11,weight:'600'},callback:function(value){return String(this.getLabelForValue(value)).replace(/^ห้อง\s*/,'')}},title:{display:true,text:'ห้อง',padding:{top:6}}},y:{stacked:true,beginAtZero:true,ticks:{precision:0},title:{display:true,text:'จำนวนนักเรียน (คน)'}}}}}
function drawCharts(sum){if(typeof Chart==='undefined')return;const draw=(g,id,old,cb)=>{const rs=sum.roomRows.filter(r=>r.grade===g);if(old)old.destroy();return new Chart($(id),{type:'bar',data:{labels:rs.map(r=>'ห้อง '+r.room),datasets:[{label:'ทำแล้ว',data:rs.map(r=>r.verified),backgroundColor:'rgba(19,124,85,.82)',borderRadius:7,borderSkipped:false},{label:'ยังไม่ทำ',data:rs.map(r=>r.pending),backgroundColor:'rgba(245,158,11,.82)',borderRadius:7,borderSkipped:false}]},options:chartOpt(rs,cb)})};chartM1=draw(1,'chartM1',chartM1,openPending);chartM4=draw(4,'chartM4',chartM4,openPending)}
function publicRows(summary){const out=[];for(const g of [1,4]){const gx=summary?.by_grade?.[String(g)]||summary?.by_grade?.[g];if(!gx)continue;for(const [room,x] of Object.entries(gx.rooms||{}))out.push({grade:g,room:+room,total:+(x.total||0),verified:+(x.verified||0),pending:+(x.pending||0)})}return out.sort((a,b)=>a.grade-b.grade||a.room-b.room)}
function renderPublicSummary(summary){const total=+(summary.total||0),verified=+(summary.verified||0),pending=+(summary.pending||0),pct=total?Math.round(verified/total*100):0;$('publicKpiGrid').innerHTML=[[total,'นักเรียนทั้งหมด'],[verified,'ทำแล้ว'],[pending,'ยังไม่ทำ'],[pct+'%','ความคืบหน้า']].map(([n,l])=>`<div class="kpi"><strong>${n}</strong><span>${l}</span></div>`).join('');if(typeof Chart==='undefined')return;const rs=publicRows(summary),draw=(g,id,old)=>{const x=rs.filter(r=>r.grade===g);if(old)old.destroy();return new Chart($(id),{type:'bar',data:{labels:x.map(r=>'ห้อง '+r.room),datasets:[{label:'ทำแล้ว',data:x.map(r=>r.verified),backgroundColor:'rgba(19,124,85,.82)',borderRadius:7,borderSkipped:false},{label:'ยังไม่ทำ',data:x.map(r=>r.pending),backgroundColor:'rgba(245,158,11,.82)',borderRadius:7,borderSkipped:false}]},options:chartOpt(x,loadPublicPending)})};publicChartM1=draw(1,'publicChartM1',publicChartM1);publicChartM4=draw(4,'publicChartM4',publicChartM4);$('publicUpdated').className='public-live';$('publicUpdated').textContent='อัปเดตล่าสุด '+new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}
async function loadPublicSummary(){try{const j=await api('/public/summary');renderPublicSummary(j.summary||{})}catch(err){$('publicUpdated').className='public-live error';$('publicUpdated').textContent='ไม่สามารถโหลดสถิติได้';console.error(err)}}
async function loadPublicPending(r){$('publicPendingTitle').textContent=`รายชื่อที่ยังไม่ทำ ม.${r.grade}/${r.room}`;$('publicPendingSummary').innerHTML=`นักเรียนทั้งหมด <b>${r.total}</b> คน · ทำแล้ว <b>${r.verified}</b> คน · ยังไม่ทำ <b>${r.pending}</b> คน`;try{const j=await api(`/public/pending?grade=${r.grade}&room=${r.room}`);$('publicPendingBody').innerHTML=(j.students||[]).length?j.students.map(s=>`<tr><td>${esc(s.seat_number??'-')}</td><td>${esc(s.display_name||'-')}</td></tr>`).join(''):'<tr><td colspan="2">ทุกคนทำครบแล้ว</td></tr>';$('publicPendingModal').classList.remove('hidden')}catch(err){alert(err.message)}}
$('closePublicPendingModal').onclick=()=>$('publicPendingModal').classList.add('hidden');$('publicPendingModal').onclick=e=>{if(e.target.id==='publicPendingModal')$('publicPendingModal').classList.add('hidden')};
function changeMap(){const m={};changes.forEach(c=>{const id=String(c.student_id||'');if(!id)return;m[id]||=new Set();(c.changed_fields||[]).forEach(f=>m[id].add(labels[f]||f))});return m}
function fillRoomFilter(){const g=$('filterGrade').value,rs=[...new Set(activeStudents().filter(s=>!g||String(s.grade)===g).map(s=>s.room))].sort((a,b)=>a-b);$('filterRoom').innerHTML='<option value="">ทุกห้อง</option>'+rs.map(r=>`<option value="${r}">ห้อง ${r}</option>`).join('')}
function renderStudents(){const g=$('filterGrade').value,r=$('filterRoom').value,st=$('filterStatus').value,q=$('filterSearch').value.trim().toLowerCase(),cm=changeMap();const rows=students.filter(s=>(!g||String(s.grade)===g)&&(!r||String(s.room)===r)&&(!st||(st==='verified'&&s.is_active!==false&&s.verified)||(st==='pending'&&s.is_active!==false&&!s.verified)||(st==='changed'&&s.has_changes)||(st==='inactive'&&s.is_active===false))&&(!q||`${s.student_number} ${s.first_name_th} ${s.last_name_th} ${s.previous_school||''}`.toLowerCase().includes(q)));$('studentsBody').innerHTML=rows.map(s=>{const cl=[...(cm[String(s.id)]||[])].join(', '),status=s.is_active===false?'<span class="badge inactive">ย้ายออกแล้ว</span>':(s.verified?'<span class="badge ok">ทำแล้ว</span>':'<span class="badge pending">ยังไม่ทำ</span>')+(s.has_changes?' <span class="badge changed">แก้ไขแล้ว</span>':'');return`<tr><td>ม.${s.grade}/${s.room}</td><td>${esc(s.student_number)}</td><td>${esc(s.seat_number??'-')}</td><td><b>${esc(fullname(s))}</b></td><td>${esc(s.previous_school||'-')}</td><td>${status}</td><td>${cl?esc(cl):'-'}</td></tr>`}).join('')||'<tr><td colspan="7">ไม่พบข้อมูล</td></tr>'}
function renderChanges(){$('changesBody').innerHTML=changes.map(c=>{const s=c.profile_check_students||{},fs=c.changed_fields||[],details=fs.map(f=>`<div class="change-pair"><b>${esc(labels[f]||f)}</b><div class="before">${esc(c.before_data?.[f]??'')}</div><div class="after">→ ${esc(c.after_data?.[f]??'')}</div></div>`).join('');return`<tr><td>${dtime(c.changed_at)}</td><td>ม.${s.grade||'-'}/${s.room||'-'}<br><b>${esc(fullname(s))}</b><br><small>${esc(s.student_number||'')}</small></td><td>${fs.map(f=>esc(labels[f]||f)).join(', ')}</td><td>${details}</td></tr>`}).join('')||'<tr><td colspan="4">ยังไม่มีการแก้ไขข้อมูล</td></tr>'}
function renderManage(){const q=$('manageSearch').value.trim().toLowerCase(),rows=students.filter(s=>q&&`${s.student_number} ${s.first_name_th} ${s.last_name_th}`.toLowerCase().includes(q)).slice(0,30);$('manageBody').innerHTML=q?(rows.length?rows.map(s=>`<tr><td><b>${esc(fullname(s))}</b><br><small>ม.${s.grade}/${s.room} · เลขที่ ${esc(s.seat_number??'-')} · ${esc(s.student_number)}</small></td><td>${s.is_active===false?'<span class="badge inactive">ย้ายออกแล้ว</span>':'<span class="badge ok">กำลังเรียน</span>'}</td><td><div class="action-group">${s.is_active===false?`<button class="btn tiny success reactivateBtn" data-id="${s.id}">เปิดใช้งาน/ย้ายเข้า</button>`:`<button class="btn tiny ghost moveBtn" data-id="${s.id}">ย้ายห้อง</button><button class="btn tiny danger outBtn" data-id="${s.id}">ย้ายออก</button>`}</div></td></tr>`).join(''):'<tr><td colspan="3">ไม่พบข้อมูล</td></tr>'):'<tr><td colspan="3">พิมพ์ชื่อหรือเลขประจำตัวเพื่อค้นหา</td></tr>';document.querySelectorAll('.moveBtn').forEach(b=>b.onclick=()=>moveStudent(+b.dataset.id));document.querySelectorAll('.outBtn').forEach(b=>b.onclick=()=>transferOut(+b.dataset.id));document.querySelectorAll('.reactivateBtn').forEach(b=>b.onclick=()=>reactivate(+b.dataset.id))}
$('manageSearch').oninput=renderManage;
async function moveStudent(id){const s=students.find(x=>x.id===id);if(!s)return;const room=prompt(`ย้าย ${fullname(s)} จากห้อง ${s.room} ไปห้องใด?`,String(s.room));if(room===null)return;const seat=prompt('เลขที่ใหม่ (เว้นว่างหากไม่เปลี่ยน)',String(s.seat_number??''));try{await api('/admin/students/move-room',{method:'POST',body:{student_id:id,new_room:+room,new_seat_number:seat},token:adminToken});await meta();await refreshDashboard();await loadPublicSummary();alert('ย้ายห้องเรียบร้อยแล้ว')}catch(err){alert(err.message)}}
async function transferOut(id){const s=students.find(x=>x.id===id);if(!s||!confirm(`ยืนยันย้ายออก ${fullname(s)} ?\nข้อมูลจะถูกเก็บประวัติไว้ แต่จะไม่นับในจำนวนนักเรียนปัจจุบัน`))return;try{await api('/admin/students/transfer-out',{method:'POST',body:{student_id:id},token:adminToken});await refreshDashboard();await loadPublicSummary();alert('บันทึกย้ายออกเรียบร้อยแล้ว')}catch(err){alert(err.message)}}
async function reactivate(id){const s=students.find(x=>x.id===id);if(!s)return;const room=prompt(`กำหนดห้องสำหรับ ${fullname(s)}`,String(s.room));if(room===null)return;const seat=prompt('เลขที่',String(s.seat_number??''));try{await api('/admin/students/reactivate',{method:'POST',body:{student_id:id,grade:s.grade,room:+room,seat_number:seat},token:adminToken});await meta();await refreshDashboard();await loadPublicSummary();alert('เปิดใช้งานนักเรียนเรียบร้อยแล้ว')}catch(err){alert(err.message)}}
$('addStudentForm').onsubmit=async e=>{e.preventDefault();msg('addStudentMsg','กำลังเพิ่มนักเรียน...');try{await api('/admin/students/add',{method:'POST',token:adminToken,body:{grade:+$('addGrade').value,room:+$('addRoom').value,seat_number:$('addSeat').value,student_number:$('addNumber').value.trim(),prefix_th:$('addPrefix').value.trim(),first_name_th:$('addFirst').value.trim(),last_name_th:$('addLast').value.trim(),phone:$('addPhone').value.trim(),previous_school:$('addSchool').value.trim()}});$('addStudentForm').reset();msg('addStudentMsg','เพิ่มนักเรียนเรียบร้อยแล้ว','success');await meta();await refreshDashboard();await loadPublicSummary()}catch(err){msg('addStudentMsg',err.message,'error')}};
function openPending(r){$('pendingModalTitle').textContent=`รายชื่อที่ยังไม่ทำ ม.${r.grade}/${r.room}`;$('pendingModalSummary').innerHTML=`นักเรียนทั้งหมด <b>${r.total}</b> คน · ทำแล้ว <b>${r.verified}</b> คน · ยังไม่ทำ <b>${r.pending}</b> คน · มีการแก้ไข <b>${r.changed}</b> คน`;$('pendingStudentsBody').innerHTML=r.pendingStudents.length?r.pendingStudents.sort((a,b)=>(a.seat_number||999)-(b.seat_number||999)).map(s=>`<tr><td>${esc(s.seat_number??'-')}</td><td>${esc(s.student_number)}</td><td>${esc(fullname(s))}</td><td>${esc(s.previous_school||'-')}</td></tr>`).join(''):'<tr><td colspan="4">ทุกคนทำครบแล้ว</td></tr>';$('pendingModal').classList.remove('hidden')}
$('closePendingModal').onclick=()=>$('pendingModal').classList.add('hidden');$('pendingModal').onclick=e=>{if(e.target.id==='pendingModal')$('pendingModal').classList.add('hidden')};
function renderRooms(sum){const gf=$('roomGradeFilter').value,q=$('roomSearch').value.trim(),rs=sum.roomRows.filter(r=>(!gf||String(r.grade)===gf)&&(!q||`ม.${r.grade}/${r.room}`.includes(q)||`${r.grade}/${r.room}`.includes(q)));$('roomsBody').innerHTML=rs.map(r=>{const p=r.total?Math.round(r.verified/r.total*100):0;return`<tr><td><b>ม.${r.grade}/${r.room}</b></td><td>${r.total}</td><td>${r.verified}</td><td>${r.pending}</td><td>${r.changed}</td><td><div class="progress"><i style="width:${p}%"></i></div><small>${p}%</small></td><td><button class="room-action" data-g="${r.grade}" data-r="${r.room}">ดูรายชื่อ (${r.pending})</button></td></tr>`}).join('')||'<tr><td colspan="7">ไม่พบข้อมูล</td></tr>';document.querySelectorAll('.room-action').forEach(b=>b.onclick=()=>{const r=sum.roomRows.find(x=>x.grade===+b.dataset.g&&x.room===+b.dataset.r);if(r)openPending(r)})}
async function refreshDashboard(){const[a,c]=await Promise.all([api('/admin/students',{token:adminToken}),api('/admin/changes',{token:adminToken})]);students=a.students||[];changes=c.changes||[];const sum=roomSummary();renderTop(sum);drawCharts(sum);fillRoomFilter();renderStudents();renderChanges();renderRooms(sum);renderManage();$('lastRefresh').textContent='อัปเดตล่าสุด '+new Date().toLocaleString('th-TH')}
$('filterGrade').onchange=()=>{fillRoomFilter();renderStudents()};$('filterRoom').onchange=renderStudents;$('filterStatus').onchange=renderStudents;$('filterSearch').oninput=renderStudents;$('roomGradeFilter').onchange=()=>renderRooms(roomSummary());$('roomSearch').oninput=()=>renderRooms(roomSummary());document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab+'Tab').classList.add('active')});
$('changePinForm').onsubmit=async e=>{e.preventDefault();msg('changePinMsg','กำลังบันทึก...');try{await api('/admin/change-pin',{method:'POST',body:{new_pin:$('newAdminPin').value},token:adminToken});$('newAdminPin').value='';msg('changePinMsg','เปลี่ยนรหัสเรียบร้อยแล้ว','success')}catch(err){msg('changePinMsg',err.message,'error')}};
$('exportBtn').onclick=()=>{if(typeof XLSX==='undefined')return alert('ไม่สามารถโหลด Excel library ได้');const sum=roomSummary(),cm=changeMap();const latest=students.map(s=>({'ชั้น':s.grade,'ห้อง':s.room,'เลขที่':s.seat_number,'เลขประจำตัวนักเรียน':s.student_number,'คำนำหน้า':s.prefix_th,'ชื่อ':s.first_name_th,'สกุล':s.last_name_th,'เบอร์โทรนักเรียน':s.phone,'โรงเรียนเดิม':s.previous_school,'ทำแล้ว':s.verified?'ใช่':'ไม่','มีการแก้ไข':s.has_changes?'ใช่':'ไม่','รายการที่แก้ไข':[...(cm[String(s.id)]||[])].join(', '),'สถานะนักเรียน':s.is_active===false?'ย้ายออกแล้ว':'กำลังเรียน','วันที่ยืนยันล่าสุด':dtime(s.verified_at||s.updated_at)}));const roomRows=sum.roomRows.map(r=>({'ชั้น':r.grade,'ห้อง':r.room,'นักเรียนทั้งหมด':r.total,'ทำแล้ว':r.verified,'ยังไม่ทำ':r.pending,'มีการแก้ไข':r.changed,'ความคืบหน้า(%)':r.total?Math.round(r.verified/r.total*100):0}));const pend=sum.roomRows.flatMap(r=>r.pendingStudents.map(s=>({'ชั้น':r.grade,'ห้อง':r.room,'เลขที่':s.seat_number,'เลขประจำตัว':s.student_number,'ชื่อ-นามสกุล':fullname(s),'โรงเรียนเดิม':s.previous_school||''})));const logs=changes.flatMap(c=>(c.changed_fields||[]).map(f=>{const s=c.profile_check_students||{};return{'วันเวลา':dtime(c.changed_at),'ชั้น':s.grade,'ห้อง':s.room,'เลขประจำตัว':s.student_number,'ชื่อ-นามสกุล':fullname(s),'รายการที่แก้ไข':labels[f]||f,'ข้อมูลเดิม':c.before_data?.[f]??'','ข้อมูลใหม่':c.after_data?.[f]??''}}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(latest),'ข้อมูลล่าสุด');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(roomRows),'สรุปรายห้อง');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(pend),'คนที่ยังไม่ทำ');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(logs),'ประวัติการแก้ไข');XLSX.writeFile(wb,'สรุประบบตรวจสอบโรงเรียนเดิม.xlsx')};
(async()=>{await meta();await loadPublicSummary();if(studentToken){try{const j=await api('/student/me',{token:studentToken});loadStudent(j.student);showView('studentEditView');return}catch{studentToken='';sessionStorage.removeItem('studentToken')}}if(adminToken){try{await refreshDashboard();showView('teacherDashboardView');return}catch{adminToken='';sessionStorage.removeItem('adminToken')}}showView('studentLoginView')})();